services:
  auth-service:
    build: ./auth_service
    ports:
      - "8000:8000"
    networks:
      - my_network

  file-upload:
    build: ./file-upload
    ports:
      - "8001:8001"
    networks:
      - my_network
    depends_on:
      - auth-service

networks:
  my_network:
    driver: bridge
